$(
  MDE Pyramid with Resolved Metas - Metamath Implementation
  All moduli parameters are explicitly instantiated
  This provides a complete, compilable Metamath library
  
  Generated by metamath-generator.rkt
  $)

$( MDE Pyramid with Resolved Metas - Metamath Implementation $)
$( All moduli parameters are explicitly instantiated $)
$( This provides a complete, compilable Metamath library $)

$( Import all resolved modules $)
$[ M3Metamath.mm $]
$[ RGMetamath.mm $]
$[ TestsMetamath.mm $]

$( Main library exports $)
$( All components are re-exported for easy access $)
$( Moduli are resolved with concrete values: $)
$( mu1=1, mu2=2, mu3=3, mu4=4 $)
$( mu1star=1, mu2star=2, mu3star=3, mu4star=4 $)
$( lambda=1, lambdastar=1 $)

$c mde-pyramid-complete $.

$( Library completeness proof $)
mde-pyramid-complete $p function mde-pyramid-complete $=
  ( concrete-moduli rg-flow-def rg-beta-function-def rg-anomaly-measure-def ) ABC $.

