$(
  MDE Pyramid with Resolved Metas - Metamath Implementation
  All moduli parameters are explicitly instantiated
  This provides a complete, compilable Metamath library
  
  Generated by metamath-generator.rkt
  $)

$( Tests with Resolved Metas $)
$( All test functions use concrete moduli values $)

$c rg-flow-test rg-beta-test rg-anomaly-test $.
$c consistency-theorem compactness-theorem completeness-theorem $.
$c soundness-theorem coherence-theorem $.
$c goedel-theorem-test tarski-theorem-test rice-theorem-test $.
$c noether-theorem-test ward-theorem-test $.
$c rg-truth-system-test rg-consistency-test rg-truth-convergence-test $.
$c rg-type-preservation theorem-helpers-well-typed $.
$c rg-flow-composition-test $.

$v test-input test-output $.
test-input-is-value $f value test-input $.
test-output-is-value $f value test-output $.

$( Unit Tests with Resolved Metas $)
$( RG Flow Test $)
rg-flow-test-def $a function rg-flow-test $.
rg-flow-test-preserves $p function rg-flow-test $=
  ( test-input-is-value ) A $.

$( RG Beta Function Test $)
rg-beta-test-def $a function rg-beta-test $.
rg-beta-test-preserves $p function rg-beta-test $=
  ( test-input-is-value ) A $.

$( RG Anomaly Measure Test $)
rg-anomaly-test-def $a function rg-anomaly-test $.
rg-anomaly-test-preserves $p function rg-anomaly-test $=
  ( test-input-is-value ) A $.

$( Integration Tests with Resolved Metas $)
$( RG Flow Composition Test $)
rg-flow-composition-test-def $a function rg-flow-composition-test $.
rg-flow-composition-test-preserves $p function rg-flow-composition-test $=
  ( function-is-function function-is-function test-input-is-value ) ABC $.

$( Theorem Proof Obligations with Resolved Metas $)
$( Consistency Theorem $)
consistency-theorem-def $a function consistency-theorem $.
consistency-theorem-preserves $p function consistency-theorem $=
  ( test-input-is-value ) A $.

$( Compactness Theorem $)
compactness-theorem-def $a function compactness-theorem $.
compactness-theorem-preserves $p function compactness-theorem $=
  ( test-input-is-value ) A $.

$( Completeness Theorem $)
completeness-theorem-def $a function completeness-theorem $.
completeness-theorem-preserves $p function completeness-theorem $=
  ( test-input-is-value ) A $.

$( Soundness Theorem $)
soundness-theorem-def $a function soundness-theorem $.
soundness-theorem-preserves $p function soundness-theorem $=
  ( test-input-is-value ) A $.

$( Coherence Theorem $)
coherence-theorem-def $a function coherence-theorem $.
coherence-theorem-preserves $p function coherence-theorem $=
  ( test-input-is-value ) A $.

$( Mathematical Power Tests with Resolved Metas $)
$( Godel Theorem Test $)
goedel-theorem-test-def $a function goedel-theorem-test $.
goedel-theorem-test-preserves $p function goedel-theorem-test $=
  ( test-input-is-value ) A $.

$( Tarski Theorem Test $)
tarski-theorem-test-def $a function tarski-theorem-test $.
tarski-theorem-test-preserves $p function tarski-theorem-test $=
  ( test-input-is-value ) A $.

$( Rice Theorem Test $)
rice-theorem-test-def $a function rice-theorem-test $.
rice-theorem-test-preserves $p function rice-theorem-test $=
  ( test-input-is-value ) A $.

$( Noether Theorem Test $)
noether-theorem-test-def $a function noether-theorem-test $.
noether-theorem-test-preserves $p function noether-theorem-test $=
  ( test-input-is-value ) A $.

$( Ward Theorem Test $)
ward-theorem-test-def $a function ward-theorem-test $.
ward-theorem-test-preserves $p function ward-theorem-test $=
  ( test-input-is-value ) A $.

$( RG Truth System Tests with Resolved Metas $)
$( RG Truth System Test $)
rg-truth-system-test-def $a function rg-truth-system-test $.
rg-truth-system-test-preserves $p function rg-truth-system-test $=
  ( test-input-is-value ) A $.

$( RG Consistency Test $)
rg-consistency-test-def $a function rg-consistency-test $.
rg-consistency-test-preserves $p function rg-consistency-test $=
  ( test-input-is-value ) A $.

$( RG Truth Convergence Test $)
rg-truth-convergence-test-def $a function rg-truth-convergence-test $.
rg-truth-convergence-test-preserves $p function rg-truth-convergence-test $=
  ( test-input-is-value ) A $.

$( Type-Safe Property Tests with Resolved Metas $)
$( Test that all RG operators preserve types $)
rg-type-preservation-def $a function rg-type-preservation $.
rg-type-preservation-preserves $p function rg-type-preservation $=
  ( function-is-function test-input-is-value ) AB $.

$( Test that theorem helpers are well-typed $)
theorem-helpers-well-typed-def $a function theorem-helpers-well-typed $.
theorem-helpers-well-typed-preserves $p function theorem-helpers-well-typed $=
  ( test-input-is-value ) A $.

