#lang racket
; (c) 2025 AI.IMPACT GmbH. Licensed under CC BY-NC-ND 4.0. Provided "as is" without warranties. No patent rights granted. Not for safety-critical use.

;; Lux unified API (native, abstract-first)

(provide (all-defined-out)
         (all-from-out (file "./foundations/abstract-core.rkt"))
         (all-from-out (file "./algebra/algebraic-structures.rkt"))
         (all-from-out (file "./algebra/central-scalars.rkt"))
         (all-from-out (file "./algebra/explog-decomposition.rkt"))
         (all-from-out (file "./algebra/braided-operators.rkt"))
         (all-from-out (file "./algebra/boundary-decomposition.rkt"))
         (all-from-out (file "./algebra/auxiliary-transporters.rkt"))
         (all-from-out (file "./foundation/v2-axioms.rkt"))
         (all-from-out (file "./logic/guarded-negation.rkt"))
         (all-from-out (file "./logic/internal-coding.rkt"))
         (all-from-out (file "./logic/internalize.rkt"))
         (all-from-out (file "./logic/proof.rkt"))
         (all-from-out (file "./logic/incompleteness.rkt"))
         (all-from-out (file "./logic/rice-generalization.rkt"))
         (all-from-out (file "./logic/inference.rkt"))
         (all-from-out (file "./logic/kernel.rkt"))
         (all-from-out (file "./logic/quantifiers.rkt"))
         (all-from-out (file "./theorems/logic-properties.rkt"))
         (all-from-out (file "./theorems/lifting.rkt"))
         (all-from-out (file "./theorems/truth.rkt"))
         (all-from-out (file "./theorems/gap.rkt"))
         (all-from-out (file "./set/zfc.rkt"))
         (all-from-out (file "./logic/conservativity.rkt"))
         (all-from-out (file "./ports/domain-registry.rkt"))
         (all-from-out (file "./ports/analytic-number-theory/rc-scheme.rkt"))
         (all-from-out (file "./ports/analytic-number-theory/zeta-gf.rkt"))
         (all-from-out (file "./ports/analytic-number-theory/evidence.rkt"))
         (all-from-out (file "./ports/analytic-number-theory/symbolic-dirichlet.rkt"))
         (all-from-out (file "./ports/analytic-number-theory/symbolic-evidence.rkt"))
         (all-from-out (file "./ports/complexity-theory.rkt"))
         (all-from-out (file "./physics/feynman-path-integral.rkt"))
         (all-from-out (file "./moduli/moduli-system.rkt"))
         (all-from-out (file "./theorems/generating-functionals.rkt"))
         (all-from-out (file "./theorems/categorical-logic.rkt"))
         (all-from-out (file "./verification/verify.rkt")))

;; Base abstract layer
(require (file "./foundations/abstract-core.rkt")
         (file "./foundations/abstract-intervals.rkt"))

;; Algebra layers (native)
(require (file "./algebra/algebraic-structures.rkt")
         (file "./algebra/central-scalars.rkt")
         (file "./algebra/explog-decomposition.rkt")
         (file "./algebra/braided-operators.rkt")
         (file "./algebra/boundary-decomposition.rkt")
         (file "./algebra/auxiliary-transporters.rkt")
         (file "./foundation/v2-axioms.rkt"))

;; Logic layer (native)
(require (file "./logic/guarded-negation.rkt")
         (file "./logic/internal-coding.rkt"))

;; Local ports and physics
(require (file "./ports/domain-registry.rkt")
         (file "./physics/feynman-path-integral.rkt")
         (file "./moduli/moduli-system.rkt")
         (file "./ports/analytic-number-theory/rc-scheme.rkt")
         (file "./ports/analytic-number-theory/zeta-gf.rkt")
         (file "./ports/analytic-number-theory/evidence.rkt")
         (file "./ports/analytic-number-theory/symbolic-dirichlet.rkt")
         (file "./ports/analytic-number-theory/symbolic-evidence.rkt")
         (file "./ports/complexity-theory.rkt"))

;; Keep domain ports and physics view via original modules (to be migrated next)
;; Done
